version: 2
jobs:
  build:
    working_directory: ~/electron-redux
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - electron-redux-{{ .Branch }}
            - electron-redux-
      - run:
          name: Install Dependencies
          command: yarn && ./node_modules/.bin/lerna bootstrap
      - save_cache:
          key: electron-redux-{{ .Branch }}
          paths:
            - "~/.cache/yarn"
            - "~/electron-redux/node_modules"
            - "~/electron-redux/packages/electron-redux/node_modules"
            - "~/electron-redux/packages/electron-redux-e2e/node_modules"
      - run:
          name: Update yarn lockfile
          command: ./node_modules/.bin/greenkeeper-lockfile-update
      - run:
          name: Compile Assets
          command: ./node_modules/.bin/lerna run build
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Upload yarn lockfile
          command: ./node_modules/.bin/greenkeeper-lockfile-upload
      - store_artifacts:
          path: ~/electron-redux/packages/electron-redux/dist
          destination: dist
      - store_artifacts:
          path: ~/electron-redux/packages/electron-redux/node_modules/coverage
          destination: coverage
